; Конфигурация лупы
; Значения командной строки имеют приоритет над этим файлом.
; Закрыть приложение: клавиша Escape

; Радиус окружности лупы в пикселях (20..800)
radius=150

; Кратность увеличения (1.1..20.0)
zoom=2.0

; Частота обновления в кадрах/сек (5..60)
; На слабом ПК уменьшите до 15-20
fps=30
